vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build_test:
    <<: *vse
    steps:
      - checkout
      - add_ssh_keys
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - ansible
  deploy:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible boto boto3
      - run: chmod 400 final.pem
      - run: ansible all --list-hosts
      - run: ansible-playbook ./ansible/ec2deploy.yml --user=ubuntu --key-file=final.pem

workflows:
  version: 2.1
  build:
    jobs:
      - build_test
      - deploy:
         requires:
            - build_test
         filters:
            branches:
               only: master
